### ISSUE TITLE
Can't install auto-shutdown-extension due to yarn error

### ISSUE THREAD

**Issue by dh-nickbilozerov** [aws-samples/sagemaker-studio-auto-shutdown-extension#13]
After running the command 
```
./install_tarball.sh
```
I receive the following error

```
Processing ./sagemaker_studio_autoshutdown-0.1.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: boto3>=1.10.44 in /opt/conda/lib/python3.7/site-packages (from sagemaker-studio-autoshutdown==0.1.0) (1.18.6)
Requirement already satisfied: botocore<1.22.0,>=1.21.6 in /opt/conda/lib/python3.7/site-packages (from boto3>=1.10.44->sagemaker-studio-autoshutdown==0.1.0) (1.21.6)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in /opt/conda/lib/python3.7/site-packages (from boto3>=1.10.44->sagemaker-studio-autoshutdown==0.1.0) (0.5.0)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.7/site-packages (from boto3>=1.10.44->sagemaker-studio-autoshutdown==0.1.0) (0.9.5)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /opt/conda/lib/python3.7/site-packages (from botocore<1.22.0,>=1.21.6->boto3>=1.10.44->sagemaker-studio-autoshutdown==0.1.0) (1.25.9)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.7/site-packages (from botocore<1.22.0,>=1.21.6->boto3>=1.10.44->sagemaker-studio-autoshutdown==0.1.0) (2.8.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.22.0,>=1.21.6->boto3>=1.10.44->sagemaker-studio-autoshutdown==0.1.0) (1.14.0)
DEPRECATION: Source distribution is being reinstalled despite an installed package having the same name and version as the installed package. pip 21.1 will remove support for this functionality. A possible replacement is use --force-reinstall. You can find discussion regarding this at https://github.com/pypa/pip/issues/8711.
Building wheels for collected packages: sagemaker-studio-autoshutdown
  Building wheel for sagemaker-studio-autoshutdown (PEP 517) ... done
  Created wheel for sagemaker-studio-autoshutdown: filename=sagemaker_studio_autoshutdown-0.1.0-py3-none-any.whl size=20563 sha256=e89937ac8336de78c9b87f44a7ccfb08ce1c3269464a08f8478ec9d852721779
  Stored in directory: /home/sagemaker-user/.cache/pip/wheels/b3/38/f9/54312a8fe95552bbe8658323cd9b8dfaaf1254f5d09a161d59
Successfully built sagemaker-studio-autoshutdown
Installing collected packages: sagemaker-studio-autoshutdown
  Attempting uninstall: sagemaker-studio-autoshutdown
    Found existing installation: sagemaker-studio-autoshutdown 0.1.0
    Uninstalling sagemaker-studio-autoshutdown-0.1.0:
      Successfully uninstalled sagemaker-studio-autoshutdown-0.1.0
Successfully installed sagemaker-studio-autoshutdown-0.1.0
yarn config v1.15.2
success Set "cache-folder" to "/tmp/yarncache".
Done in 0.04s.
[LabBuildApp] Searching ['/home/sagemaker-user/.auto-shutdown', '/home/sagemaker-user/.jupyter', '/opt/conda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[LabBuildApp] Looking for jupyter_config in /etc/jupyter
[LabBuildApp] Looking for jupyter_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /opt/conda/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /home/sagemaker-user/.jupyter
[LabBuildApp] Looking for jupyter_config in /home/sagemaker-user/.auto-shutdown
[LabBuildApp] Looking for JupyterLab_config in /etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /opt/conda/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /home/sagemaker-user/.jupyter
[LabBuildApp] Looking for JupyterLab_config in /home/sagemaker-user/.auto-shutdown
[LabBuildApp] JupyterLab 1.2.20
[LabBuildApp] Building in /opt/conda/share/jupyter/lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v12.16.1

[LabBuildApp] Building jupyterlab assets (build:prod)
[LabBuildApp] > node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
|[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find package "@amzn/sagemaker-ui-activation-monitor-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
warning @amzn/sagemaker-ui > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @amzn/sagemaker-ui > aws-sdk > uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @amzn/sagemaker-ui > react-jsonschema-form > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning @amzn/sagemaker-ui > react-jsonschema-form > @babel/runtime-corejs2 > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning @amzn/sagemaker-ui > vega-lite > @types/fast-json-stable-stringify@2.1.0: This is a stub types definition. fast-json-stable-stringify provides its own type definitions, so you do not need this installed.
warning @amzn/sagemaker-ui > compassql > vega-lite > @types/fast-json-stable-stringify@2.1.0: This is a stub types definition. fast-json-stable-stringify provides its own type definitions, so you do not need this installed.
warning @amzn/sagemaker-ui > compassql > datalib > topojson@1.6.27: Use topojson-client, topojson-server or topojson-simplify directly.
warning @amzn/sagemaker-ui > compassql > datalib > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @amzn/sagemaker-ui > compassql > datalib > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @amzn/sagemaker-ui > compassql > datalib > request > har-validator@5.1.5: this library is no longer supported
Error: Couldn't find package "@amzn/sagemaker-ui-automl-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-data-prep-plugin@1.10.0" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-constants@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-components@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-debugger-plugin@0.4.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-appstate-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-emr-cluster-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-graphql-components@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-jumpstart-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-kernel-gql-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-graphql-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-feature-flags-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-graphql-client@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-kernel-status-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-log-event@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-logger-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-property-inspector-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-remote-status-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-sagemaker-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-remote-terminals-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-penny-client-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-schema-types@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-shutdown-menu-plugin@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-types@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-utils@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-xai@3.10.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.10.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 660, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

An error occured.
RuntimeError: npm dependencies failed to install
```

**Comment by garzoand** [comment]
Thank you for submitting this ticket. Wondering, are you using any private/custom NPM repository from studio? If yes, would it be possible to turn it off while you are running the install script? Unfortunately, due to a yarn issue, if a private repository is set up, it does not pick the packages up available locally, therefore the installation will be unsuccessful.

**Comment by rthamman** [comment]
@dh-nickbilozerov let us know if you are still running into this issue. We'll close the case and reopen based on your response.
