### ISSUE TITLE
Simple installation not working

### ISSUE THREAD

**Issue by jperuggia** [aws-samples/sagemaker-studio-auto-shutdown-extension#23]
I am attempting to install the LCC for timeout / idle shutdown and doing so via the provided default script and using boto3 to set it up. 

Python Code to create lifecycle and set as default:

```
import base64
script_file = 'on-jupyter-server-start.sh' # provided by AWS
data = open(script_file, "r").read()
encoded_data = base64.b64encode(data.encode('ascii'))
encoded_data = encoded_data.decode("utf-8")

import boto3
sm_client = boto3.client('sagemaker')
studio_domain_id = 'YOUR STUDIO DOMAIN ID'

lcc_response = sm_client.create_studio_lifecycle_config(
    StudioLifecycleConfigName='studio-auto-terminate',
    StudioLifecycleConfigContent=encoded_data,
    StudioLifecycleConfigAppType='KernelGateway',
    Tags=[
        { 
            'Key': 'Description',
            'Value': 'Sagemaker Lifecycle Config for Auto Shutdown'
        }
    ]
)


update_response = sm_client.update_domain(
    DomainId=studio_domain_id,
    DefaultUserSettings={ 
        'JupyterServerAppSettings': {
            "DefaultResourceSpec": { 
                "InstanceType": "system",
                "LifecycleConfigArn": lcc_response['StudioLifecycleConfigArn']
            },
            'LifecycleConfigArns': [
                lcc_response['StudioLifecycleConfigArn']
            ]
        },
    }
)

```

I then use the [code](https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension/blob/main/check_idle_timeout_configuration.py) provided to check for installation success and am getting this error:

```
{'idle_time': 3600, 'keep_terminals': False, 'count': 71, 'errors': 'Traceback (most recent call last):\n  File "/home/sagemaker-user/.auto-shutdown/sagemaker_studio_autoshutdown-0.1.5/sagemaker_studio_autoshutdown/idle_checker.py", line 58, in run_idle_checks\n    await self.idle_checks()\n  File "/home/sagemaker-user/.auto-shutdown/sagemaker_studio_autoshutdown-0.1.5/sagemaker_studio_autoshutdown/idle_checker.py", line 217, in idle_checks\n    apps_info = await self.build_app_info()\n  File "/home/sagemaker-user/.auto-shutdown/sagemaker_studio_autoshutdown-0.1.5/sagemaker_studio_autoshutdown/idle_checker.py", line 135, in build_app_info\n    apps = await self.get_apps()\n  File "/home/sagemaker-user/.auto-shutdown/sagemaker_studio_autoshutdown-0.1.5/sagemaker_studio_autoshutdown/idle_checker.py", line 128, in get_apps\n    response = await self.tornado_client.fetch(url, method="GET")\ntornado.httpclient.HTTPClientError: HTTP 500: Internal Server Error\n'}
```

**Comment by durgasury** [comment]
Hi @jperuggia, when you're creating the lcc script, please update the app type to JupyterServer, i.e.,
 `StudioLifecycleConfigAppType='JupyterServer'`

The extension runs on the default JupyterServer app and manages the KernelGateway apps. Let me know if that resolves it, (as well as running the [test code](https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension/blob/main/check_idle_timeout_configuration.py) from a System terminal, not a notebook/image terminal)
