### ISSUE TITLE
ValueError: Python version 3.10 unsupported

### ISSUE THREAD

**Issue by anthonydandrea** [aws-samples/sagemaker-studio-auto-shutdown-extension#50]
When executing the script [on-jupyter-server-start.sh](https://github.com/aws-samples/sagemaker-studio-lifecycle-config-examples/blob/main/scripts/install-autoshutdown-server-extension/on-jupyter-server-start.sh) in Sagemaker Studio (which installs [sagemaker_studio_autoshutdown-0.1.5](https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension/raw/main/sagemaker_studio_autoshutdown-0.1.5.tar.gz)), I get the following error in my `LifecycleConfigOnStart` logs:

```
Obtaining file:///home/.auto-shutdown/sagemaker_studio_autoshutdown-0.1.5
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/build_meta.py", line 454, in prepare_metadata_for_build_editable
          return self.prepare_metadata_for_build_wheel(
        File "/opt/conda/lib/python3.10/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 732, in <module>
        File "<string>", line 113, in ensure_python
      ValueError: Python version 3.10 unsupported
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
```

Does the package need to be updated to accept Python 3.10 environments? The `pyproject.toml` of the `sagemaker_studio_autoshutdown-0.1.5` module does not list 3.10 and I'm wondering if adding that will resolve this problem.

**Comment by anthonydandrea** [comment]
Seems like the issue is with this function: https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension/blob/main/setup.py#L98-L113

**Comment by anthonydandrea** [comment]
![Screenshot 2023-08-24 at 2 51 41 PM](https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension/assets/12243025/082ec6dc-de0d-4cbe-a4fe-08066f6f8620)

The issue is using mathematical evaluation to compare the version

**Comment by DHS-OEDA** [comment]
I am meeting with AWS today to detail the problem and hopefully have an official solution. I will update this thread with what I learn.

**Comment by jmeisele** [comment]
Any updates on this? Seems like a simple fix, after updating to the new sagemaker studio (which defaults to Python 3.10) this is now useless

**Comment by stegarth** [comment]
I managed to get around this particular issue by "updating" the [ensure_python function](https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension/blob/main/setup.py#L98-L113) as pointed out by @anthonydandrea in their [comment above](https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension/issues/50#issuecomment-1692236558)

Essentially my LCC rewrites that part of the `setup.py` via following:
```
#!/bin/bash
set -eux

mkdir -p .auto-shutdown
curl -L https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension/raw/main/sagemaker_studio_autoshutdown-0.1.5.tar.gz --output .auto-shutdown/extension.tar.gz
# update the setup script
OLDDIR=$PWD

cd .auto-shutdown
tar -xf extension.tar.gz --no-same-owner
mv sagemaker_studio_autoshutdown-0.1.5/setup.py sagemaker_studio_autoshutdown-0.1.5/setup.py.bak
N0=$(( $(grep -n 'def ensure_python' sagemaker_studio_autoshutdown-0.1.5/setup.py.bak | cut -d':' -f 1) - 1 ))
N1=$(( $(grep -n 'Python version %s' sagemaker_studio_autoshutdown-0.1.5/setup.py.bak | cut -d':' -f 1) + 1 ))
{
head -n $N0 sagemaker_studio_autoshutdown-0.1.5/setup.py.bak
cat <<EOF
def ensure_python(specs):
    """Given a list of range specifiers for python, ensure compatibility.
    """
    import re
    from pkg_resources import parse_version
    ver = re.compile(r"(?P<comp>[=><]{1,2})(?P<vstr>[0-9\.]+)")
    if not isinstance(specs, (list, tuple)):
        specs = [specs]
    v = sys.version_info
    part = "%s.%s" % (v.major, v.minor)
    for spec in specs:
        if part == spec:
            return
        try:
            comp, vstr = ver.search(spec).groups()
            if eval(f"parse_version('{part}') {comp} parse_version('{vstr}')"):
                return
        except SyntaxError:
            pass
    raise ValueError("Python version %s unsupported" % part)
EOF
tail -n +$N1 sagemaker_studio_autoshutdown-0.1.5/setup.py.bak
} > sagemaker_studio_autoshutdown-0.1.5/setup.py
tar -zcf extension.tar.gz sagemaker_studio_autoshutdown-0.1.5/
cd $OLDDIR

pip install .auto-shutdown/extension.tar.gz
jlpm config set cache-folder /tmp/yarncache
jupyter lab build --debug --minimize=False

# restarts jupter server
nohup supervisorctl -c /etc/supervisor/conf.d/supervisord.conf restart jupyterlabserver
```
However now I'm facing an issue stating:
> ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).

Which I suspect is caused by a missing `conda activate studio` command.  If I iron that out then I'll post that here too

**Comment by jmeisele** [comment]
Looks related https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension/issues/52
