### ISSUE TITLE
Manual install on SageMaker Studio instance in VPC failing

### ISSUE THREAD

**Issue by wags1999** [aws-samples/sagemaker-studio-auto-shutdown-extension#9]
I've been able to install the extension in an account I have that has Internet access without a problem.

However, I'm trying to install the extension into a SageMaker Studio that is on our VPC, with no Internet access.  I get the code onto the SageMaker Studio instance, and then run the following to point package managers at our internal Artifactory server:

```
pip config set global.index-url "https://artifactory.sentry.com/artifactory/api/pypi/pypi-virtual/simple"
jlpm config set registry "https://artifactory.sentry.com/artifactory/api/npm/npm-virtual/"
npm config set registry "https://artifactory.sentry.com/artifactory/api/npm/npm-virtual/"
```

However, when I run ./install_tarball.sh, I get the following error, and subsequent failure.  

`error Couldn't find package "@amzn/sagemaker-ui-activation-monitor-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.`

I don't see @amzn/sagemaker-ui-activation-monitor-plugin@3.7.1 in the public https://registry.npmjs.org nor in our private Artifactory mirror. Is there another repository that hosts this package?

Or if you have any other ideas for troubleshooting?  The full output is below.

```
bash-4.2$ ./install_tarball.sh
Looking in indexes: https://artifactory.sentry.com/artifactory/api/pypi/pypi-virtual/simple
Processing ./sagemaker_studio_autoshutdown-0.1.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting boto3>=1.10.44
  Using cached https://artifactory.sentry.com/artifactory/api/pypi/pypi-virtual/packages/packages/00/06/98ed8ba0bda742a04014cc97c7a76c75a463bed0ba0f0b38022041be69b8/boto3-1.17.99-py2.py3-none-any.whl (131 kB)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.7/site-packages (from boto3>=1.10.44->sagemaker-studio-autoshutdown==0.1.0) (0.9.5)
Requirement already satisfied: s3transfer<0.5.0,>=0.4.0 in /opt/conda/lib/python3.7/site-packages (from boto3>=1.10.44->sagemaker-studio-autoshutdown==0.1.0) (0.4.2)
Collecting botocore<1.21.0,>=1.20.99
  Using cached https://artifactory.sentry.com/artifactory/api/pypi/pypi-virtual/packages/packages/7b/e0/1c0df6c6f7af9b1db6dac1eae570cf7d2858f014ed6b28b1a0cb51160d57/botocore-1.20.99-py2.py3-none-any.whl (7.6 MB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.7/site-packages (from botocore<1.21.0,>=1.20.99->boto3>=1.10.44->sagemaker-studio-autoshutdown==0.1.0) (2.8.0)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /opt/conda/lib/python3.7/site-packages (from botocore<1.21.0,>=1.20.99->boto3>=1.10.44->sagemaker-studio-autoshutdown==0.1.0) (1.25.9)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.21.0,>=1.20.99->boto3>=1.10.44->sagemaker-studio-autoshutdown==0.1.0) (1.14.0)
Building wheels for collected packages: sagemaker-studio-autoshutdown
  Building wheel for sagemaker-studio-autoshutdown (PEP 517) ... done
  Created wheel for sagemaker-studio-autoshutdown: filename=sagemaker_studio_autoshutdown-0.1.0-py3-none-any.whl size=18630 sha256=31e087e2069dbb48a2af8d8e4923182a3543b4d12629b171d60cf7a52e63ca4d
  Stored in directory: /home/sagemaker-user/.cache/pip/wheels/86/72/26/e5968726fe13db61224e0c6313fd8506755d32b6a1817fe8cf
Successfully built sagemaker-studio-autoshutdown
Installing collected packages: botocore, boto3, sagemaker-studio-autoshutdown
  Attempting uninstall: botocore
    Found existing installation: botocore 1.20.89
    Uninstalling botocore-1.20.89:
      Successfully uninstalled botocore-1.20.89
  Attempting uninstall: boto3
    Found existing installation: boto3 1.10.14
    Uninstalling boto3-1.10.14:
      Successfully uninstalled boto3-1.10.14
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
awscli 1.19.89 requires botocore==1.20.89, but you have botocore 1.20.99 which is incompatible.
aiobotocore 0.11.1 requires botocore<1.13.15,>=1.13.14, but you have botocore 1.20.99 which is incompatible.
Successfully installed boto3-1.17.99 botocore-1.20.99 sagemaker-studio-autoshutdown-0.1.0
yarn config v1.15.2
success Set "cache-folder" to "/tmp/yarncache".
Done in 0.06s.
[LabBuildApp] Searching ['/home/sagemaker-user/sagemaker-studio-auto-shutdown-extension', '/home/sagemaker-user/.jupyter', '/opt/conda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[LabBuildApp] Looking for jupyter_config in /etc/jupyter
[LabBuildApp] Looking for jupyter_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /opt/conda/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /home/sagemaker-user/.jupyter
[LabBuildApp] Looking for jupyter_config in /home/sagemaker-user/sagemaker-studio-auto-shutdown-extension
[LabBuildApp] Looking for JupyterLab_config in /etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /opt/conda/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /home/sagemaker-user/.jupyter
[LabBuildApp] Looking for JupyterLab_config in /home/sagemaker-user/sagemaker-studio-auto-shutdown-extension
[LabBuildApp] JupyterLab 1.2.20
[LabBuildApp] Building in /opt/conda/share/jupyter/lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v12.16.1

[LabBuildApp] Building jupyterlab assets (build:prod)
[LabBuildApp] > node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
-[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find package "@amzn/sagemaker-ui-activation-monitor-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
warning @amzn/sagemaker-ui > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @amzn/sagemaker-ui > aws-sdk > uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @amzn/sagemaker-ui > react-jsonschema-form > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning @amzn/sagemaker-ui > react-jsonschema-form > @babel/runtime-corejs2 > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning @amzn/sagemaker-ui > vega-lite > @types/fast-json-stable-stringify@2.1.0: This is a stub types definition. fast-json-stable-stringify provides its own type definitions, so you do not need this installed.
warning @amzn/sagemaker-ui > compassql > vega-lite > @types/fast-json-stable-stringify@2.1.0: This is a stub types definition. fast-json-stable-stringify provides its own type definitions, so you do not need this installed.
warning @amzn/sagemaker-ui > compassql > datalib > topojson@1.6.27: Use topojson-client, topojson-server or topojson-simplify directly.
warning @amzn/sagemaker-ui > compassql > datalib > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @amzn/sagemaker-ui > compassql > datalib > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @amzn/sagemaker-ui > compassql > datalib > request > har-validator@5.1.5: this library is no longer supported
Error: Couldn't find package "@amzn/sagemaker-ui-data-prep-plugin@1.7.2" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-debugger-plugin@0.4.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-components@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-emr-cluster-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-graphql-client@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-graphql-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-instance-metrics-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-jumpstart-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-automl-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-graphql-components@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-logger-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-feature-flags-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-appstate-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-property-inspector-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-remote-terminals-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-kernel-status-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-kernel-gql-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-shutdown-menu-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-types@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-constants@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-xai@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-log-event@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-penny-client-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-remote-status-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-sagemaker-plugin@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-schema-types@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-utils@3.7.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-3.7.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 660, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-m9kzx35f.log
[LabBuildApp] Exiting application: JupyterLab
#######################################################
The installation was successful. This terminal window will close in 10 seconds. Refresh your IDE to see the extension on the sidebar.
nohup: ignoring input and appending output to ‘nohup.out’
^C
```

**Comment by garzoand** [comment]
Thank you for let us now. We will look into this soon and will share the update.

**Comment by garzoand** [comment]
I believe this is actually a yarn (package manager) issue: [https://github.com/yarnpkg/yarn/issues/4623](https://github.com/yarnpkg/yarn/issues/4623)

We'll let you know when we have a workaround for this.

**Comment by wags1999** [comment]
Any progress on a work-around for this issue?  We'd like to use the auto-shutdown extension, but our Enterprise has strict requirements within our AWS accounts that don't allow direct Internet access.  Seeing as the yarn issue has been open for 4 years, can the dependencies be resolved through a different package manager?

**Comment by rthamman** [comment]
We have a slim down extension version that does not need Internet access during installation. Please use this script - https://github.com/aws-samples/sagemaker-studio-lifecycle-config-examples/blob/main/scripts/install-autoshutdown-server-extension/on-jupyter-server-start.sh. 

We also launched Lifecycle Configuration (LCC) support for SageMaker studio. You can add the above script to JupyterServer LCC. See this doc link for more information - https://docs.aws.amazon.com/sagemaker/latest/dg/studio-lcc.html. This will allow you to automate and eliminate manual steps.

Let us know how it goes.

**Comment by rthamman** [comment]
Closing the issue. Please reopen if need be.
